"""Phase 2 — Translate: source schema -> target DDL, 1:1, via the flavor mapping.

Deterministic. Emits phase2/target/ddl/*.sql, phase2/unmapped_features.json (nothing dropped
silently), phase2/flag_manifest.json, and phase2/ported_code/{original,ported}/ for in-DB code.
Mapping reference: docs/db-conversion/flavor/sqlserver-to-postgresql.md. See artifacts.md.
"""
from __future__ import annotations

import re

from common import parse_args, read_json, refuse_overwrite, seal, write_json, write_text

FLAG = object()  # sentinel: type needs a human decision


def ident(name: str) -> str:
    return '"' + name.lower().replace('"', '""') + '"'


def map_type(col: dict, override: str | None):
    """Return a Postgres type string, or FLAG with a reason."""
    if override:
        return override
    t = col["type"].lower()
    length, prec, scale = col["length"], col["precision"], col["scale"]
    simple = {"bit": "boolean", "tinyint": "smallint", "smallint": "smallint", "int": "integer",
              "bigint": "bigint", "real": "real", "date": "date", "time": "time",
              "uniqueidentifier": "uuid", "xml": "xml", "smalldatetime": "timestamp(0)",
              "text": "text", "ntext": "text", "image": "bytea", "money": "numeric(19,4)",
              "smallmoney": "numeric(10,4)"}
    if t in simple:
        return simple[t]
    if t in ("decimal", "numeric"):
        return f"numeric({prec},{scale})"
    if t == "float":
        return "real" if (prec or 53) <= 24 else "double precision"
    if t in ("char", "nchar"):
        n = length // 2 if t == "nchar" else length
        return f"char({n})" if n and n > 0 else "char"
    if t in ("varchar", "nvarchar"):
        if length == -1:
            return "text"
        n = length // 2 if t == "nvarchar" else length
        return f"varchar({n})"
    if t in ("binary", "varbinary"):
        return "bytea"
    if t == "datetime":
        return "timestamp(3)"
    if t == "datetime2":
        return f"timestamp({scale})"
    if t == "datetimeoffset":
        return "timestamptz"
    if t in ("rowversion", "timestamp"):
        return (FLAG, "SQL Server row-version, not a datetime — decide bytea + versioning strategy")
    if t == "sql_variant":
        return (FLAG, "sql_variant has no faithful Postgres equivalent — decide text/jsonb (lossy)")
    if t in ("hierarchyid", "geometry", "geography"):
        return (FLAG, f"{t} is out of a pure 1:1 map — decide ltree/PostGIS")
    return (FLAG, f"unmapped source type '{t}'")


_DEFAULT_FUNCS = {
    "getdate": "now()", "sysdatetime": "now()", "current_timestamp": "now()",
    "getutcdate": "(now() at time zone 'utc')", "newid": "gen_random_uuid()",
}


def map_default(defn: str):
    """Translate a SQL Server default definition. Return (sql, flag_reason|None)."""
    expr = defn.strip()
    while expr.startswith("(") and expr.endswith(")"):
        expr = expr[1:-1].strip()
    low = expr.lower()
    if low in ("", "null"):
        return "NULL", None
    if low == "newsequentialid()":
        return "gen_random_uuid()", "NEWSEQUENTIALID(): sequentiality lost under gen_random_uuid()"
    m = re.fullmatch(r"([a-z_]+)\(\)", low)
    if m and m.group(1) in _DEFAULT_FUNCS:
        return _DEFAULT_FUNCS[m.group(1)], None
    if re.fullmatch(r"-?\d+(\.\d+)?", low):  # numeric literal
        return expr, None
    if re.fullmatch(r"n?'.*'", expr, re.DOTALL):  # string literal (drop the N prefix)
        return expr[1:] if expr[0] in "nN" else expr, None
    return expr, f"default expression not auto-translated: {defn}"


def column_ddl(col, overrides, table_key, unmapped):
    key = f"{table_key}.{col['name'].lower()}"
    if col["computed"]:
        unmapped.append({"object": key, "kind": "computed_column",
                         "source_type_or_expr": col["computed"]["expr"],
                         "reason": "computed column — verify expression transpiles; decide GENERATED/STORED or view",
                         "suggested": "GENERATED ALWAYS AS (<expr>) STORED"})
        return None  # emitted after review
    mapped = map_type(col, overrides.get(key))
    if isinstance(mapped, tuple):  # FLAG
        unmapped.append({"object": key, "kind": "type", "source_type_or_expr": col["type"],
                         "reason": mapped[1], "suggested": None})
        pg = f"/* FLAG type {col['type']} */ text"
    else:
        pg = mapped
    parts = [ident(col["name"]), pg]
    if col["identity"]:
        seed, incr = col["identity"]["seed"], col["identity"]["increment"]
        parts.append(f"GENERATED BY DEFAULT AS IDENTITY (START WITH {seed} INCREMENT BY {incr})")
    if col["default"] is not None:
        sql, reason = map_default(col["default"])
        if reason:
            unmapped.append({"object": key, "kind": "default", "source_type_or_expr": col["default"],
                             "reason": reason, "suggested": sql})
        parts.append(f"DEFAULT {sql}")
    parts.append("NULL" if col["nullable"] else "NOT NULL")
    return "  " + " ".join(parts)


def table_ddl(t, overrides, unmapped):
    key = f"{t['schema'].lower()}.{t['name'].lower()}"
    fq = f"{ident(t['schema'])}.{ident(t['name'])}"
    lines = [column_ddl(c, overrides, key, unmapped) for c in t["columns"]]
    lines = [ln for ln in lines if ln]
    if t["pk"]:
        lines.append("  PRIMARY KEY (" + ", ".join(ident(c) for c in t["pk"]) + ")")
    return f"CREATE TABLE {fq} (\n" + ",\n".join(lines) + "\n);"


def constraints_ddl(t):
    fq = f"{ident(t['schema'])}.{ident(t['name'])}"
    out = []
    for u in t["uniques"]:
        out.append(f"ALTER TABLE {fq} ADD CONSTRAINT {ident(u['name'])} "
                   f"UNIQUE (" + ", ".join(ident(c) for c in u["columns"]) + ");")
    for c in t["checks"]:
        out.append(f"-- CHECK {c['name']}: verify expression transpiles (tsql->postgres)\n"
                   f"ALTER TABLE {fq} ADD CONSTRAINT {ident(c['name'])} CHECK ({c['expr']});")
    return out


def fk_ddl(t):
    fq = f"{ident(t['schema'])}.{ident(t['name'])}"
    out = []
    for fk in t["fks"]:
        rsch, rtbl = fk["ref_table"].split(".")
        ref = f"{ident(rsch)}.{ident(rtbl)}"
        cols = ", ".join(ident(c) for c in fk["columns"])
        rcols = ", ".join(ident(c) for c in fk["ref_columns"])
        actions = ""
        if fk["on_delete"] and fk["on_delete"] != "NO_ACTION":
            actions += f" ON DELETE {fk['on_delete'].replace('_', ' ')}"
        if fk["on_update"] and fk["on_update"] != "NO_ACTION":
            actions += f" ON UPDATE {fk['on_update'].replace('_', ' ')}"
        out.append(f"ALTER TABLE {fq} ADD CONSTRAINT {ident(fk['name'])} "
                   f"FOREIGN KEY ({cols}) REFERENCES {ref} ({rcols}){actions};")
    return out


def index_ddl(t):
    fq = f"{ident(t['schema'])}.{ident(t['name'])}"
    out = []
    for ix in t["indexes"]:
        uniq = "UNIQUE " if ix["unique"] else ""
        cols = ", ".join(ident(c) for c in ix["columns"])
        incl = f" INCLUDE ({', '.join(ident(c) for c in ix['included'])})" if ix["included"] else ""
        where = f" WHERE {ix['filter']}" if ix["filter"] else ""
        out.append(f"CREATE {uniq}INDEX {ident(ix['name'])} ON {fq} ({cols}){incl}{where};")
    return out


def translate_code(cfg, objects, flags):
    import sqlglot
    for o in objects:
        base = f"{o['kind']}__{o['schema']}_{o['name']}".lower()
        write_text(cfg, f"phase2/ported_code/original/{base}.sql", o["body"])
        ported_path, auto = None, False
        if o["kind"] in ("view", "function"):
            try:
                out = sqlglot.transpile(o["body"], read="tsql", write="postgres")
                if out:
                    write_text(cfg, f"phase2/ported_code/ported/{base}.sql", ";\n".join(out) + ";")
                    ported_path, auto = f"phase2/ported_code/ported/{base}.sql", True
            except Exception:  # noqa: BLE001 — transpile failure just means it needs a human
                pass
        needs_review = (o["kind"] in ("procedure", "trigger")) or not auto
        flags.append({"name": f"{o['schema']}.{o['name']}", "kind": o["kind"],
                      "auto_translated": auto, "needs_review": needs_review,
                      "original_path": f"phase2/ported_code/original/{base}.sql",
                      "ported_path": ported_path})


def main():
    cfg, args = parse_args("Phase 2 — translate schema to target DDL")
    refuse_overwrite(cfg, args.force, "phase2/unmapped_features.json", "phase2/flag_manifest.json")
    schema = read_json(cfg, "phase1/schema.json")
    objects = read_json(cfg, "phase1/objects.json")
    overrides = {k.lower(): v for k, v in cfg.type_overrides.items()}
    in_scope = [t for t in schema["tables"]
                if f"{t['schema'].lower()}.{t['name'].lower()}" not in cfg.out_of_scope]

    unmapped: list = []
    schemas = sorted({t["schema"] for t in in_scope})
    ddl_schemas = "\n".join(f"CREATE SCHEMA IF NOT EXISTS {ident(s)};" for s in schemas if s.lower() != "public")
    ddl_tables = "\n\n".join(table_ddl(t, overrides, unmapped) for t in in_scope)
    ddl_constraints = "\n".join(c for t in in_scope for c in constraints_ddl(t))
    ddl_fks = "\n".join(c for t in in_scope for c in fk_ddl(t))
    ddl_indexes = "\n".join(c for t in in_scope for c in index_ddl(t))

    paths = [
        write_text(cfg, "phase2/target/ddl/001_schemas.sql", ddl_schemas or "-- (only public schema)"),
        write_text(cfg, "phase2/target/ddl/010_tables.sql", ddl_tables),
        write_text(cfg, "phase2/target/ddl/020_constraints.sql", ddl_constraints or "-- none"),
        write_text(cfg, "phase2/target/ddl/030_foreign_keys.sql", ddl_fks or "-- none"),
        write_text(cfg, "phase2/target/ddl/040_indexes.sql", ddl_indexes or "-- none"),
    ]

    flags: list = []
    translate_code(cfg, objects, flags)

    paths.append(write_json(cfg, "phase2/unmapped_features.json", unmapped))
    paths.append(write_json(cfg, "phase2/flag_manifest.json", flags))
    seal(cfg, *paths)
    needs = sum(1 for f in flags if f["needs_review"])
    print(f"2 translate: {len(in_scope)} tables -> DDL; {len(unmapped)} unmapped feature(s) to "
          f"decide; {len(flags)} in-DB objects ({needs} need review)")
    if unmapped or needs:
        print("  → resolve unmapped_features.json + flagged code WITH THE USER before phase 3.")


if __name__ == "__main__":
    main()
