-- Auth core schema: legacy ASP.NET Identity 2.x tables + server-side session store.
-- Applied on API startup by the schema initializer.

CREATE TABLE IF NOT EXISTS aspnetusers (
  id varchar(128) NOT NULL,
  email varchar(256) NULL,
  emailconfirmed boolean NOT NULL,
  passwordhash text NULL,
  securitystamp text NULL,
  phonenumber text NULL,
  phonenumberconfirmed boolean NOT NULL,
  twofactorenabled boolean NOT NULL,
  lockoutenddateutc timestamp(3) NULL,
  lockoutenabled boolean NOT NULL,
  accessfailedcount integer NOT NULL,
  username varchar(256) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS aspnetroles (
  id varchar(128) NOT NULL,
  name varchar(256) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS aspnetuserroles (
  userid varchar(128) NOT NULL,
  roleid varchar(128) NOT NULL,
  PRIMARY KEY (userid, roleid),
  CONSTRAINT fk_aspnetuserroles_user FOREIGN KEY (userid) REFERENCES aspnetusers(id),
  CONSTRAINT fk_aspnetuserroles_role FOREIGN KEY (roleid) REFERENCES aspnetroles(id)
);

CREATE TABLE IF NOT EXISTS userprofile (
  userprofileid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  email varchar(256) NOT NULL,
  institutionname varchar(500) NOT NULL,
  fullinstitutionname varchar(500) NOT NULL,
  countryid integer NULL,
  nationalregistrynumber varchar(25) NULL,
  internalid uuid NOT NULL,
  externalid varchar(500) NULL,
  fileid integer NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (userprofileid)
);

-- Server-side backing store for the legacy OWIN encrypted-cookie session equivalent.
-- The opaque refresh token value itself is the credential.
CREATE TABLE IF NOT EXISTS auth_sessions (
  id text PRIMARY KEY,
  user_id varchar(128) NOT NULL REFERENCES aspnetusers(id),
  security_stamp_at_issue text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
