-- Registration core schema: pre-registration verification quiz, answer catalog,
-- attempt audit log, and country catalog for the self-registration form.
-- Applied on API startup by the schema initializer.

CREATE TABLE IF NOT EXISTS question (
  questionid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  questionstring varchar(512) NOT NULL,
  "order" integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (questionid)
);

CREATE TABLE IF NOT EXISTS answer (
  answerid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  questionid integer NOT NULL,
  answerstring varchar(512) NOT NULL,
  iscorrect boolean NOT NULL,
  "order" integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (answerid),
  CONSTRAINT fk_answer_question FOREIGN KEY (questionid) REFERENCES question(questionid)
);

CREATE TABLE IF NOT EXISTS logtriedquestions (
  logtriedquestionsid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  iscorrect boolean NOT NULL,
  iptried varchar(512) NOT NULL,
  datetimetried timestamp(3) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  datetimeedit timestamp(3) NULL,
  PRIMARY KEY (logtriedquestionsid)
);

CREATE TABLE IF NOT EXISTS country (
  countryid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicscountryid varchar(128) NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (countryid)
);
