-- OSC General Data core schema: parent entity for the OSC profile wizard
-- plus the catalog tables this section depends on.
-- Applied on API startup by the schema initializer.

CREATE TABLE IF NOT EXISTS oscstatus (
  oscstatusid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsoscstatusid varchar(128) NOT NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (oscstatusid)
);

CREATE TABLE IF NOT EXISTS osctype (
  osctypeid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsosctypeid varchar(128) NOT NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (osctypeid)
);

CREATE TABLE IF NOT EXISTS osctypeconstitution (
  osctypeconstitutionid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsosctypeconstitutionid varchar(128) NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (osctypeconstitutionid)
);

CREATE TABLE IF NOT EXISTS actionline (
  actionlineid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsactionlineid varchar(128) NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (actionlineid)
);

CREATE TABLE IF NOT EXISTS actionlinesecondary (
  actionlinesecondaryid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsactionlinesecondaryid varchar(128) NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (actionlinesecondaryid)
);

CREATE TABLE IF NOT EXISTS state (
  stateid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsstateid varchar(128) NULL,
  dynamicscountryid varchar(128) NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  countryid integer NOT NULL,
  PRIMARY KEY (stateid),
  CONSTRAINT fk_state_country FOREIGN KEY (countryid) REFERENCES country(countryid)
);

CREATE TABLE IF NOT EXISTS oscprofile (
  oscprofileid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  userprofileid integer NOT NULL,
  dynamicsoscprofileid varchar(128) NULL,
  email varchar(128) NOT NULL,
  name varchar(150) NOT NULL,
  socialreason varchar(150) NOT NULL,
  osctypeid integer NOT NULL,
  actionlineid integer NULL,
  actionlinesecondaryid integer NULL,
  nationalregistrynumber varchar(25) NOT NULL,
  contactname varchar(128) NOT NULL,
  contactposition varchar(60) NOT NULL,
  contacttelephone varchar(12) NULL,
  contacttelephoneext varchar(10) NULL,
  contactemail varchar(128) NOT NULL,
  contactmobilephone varchar(12) NULL,
  countryid integer NOT NULL,
  stateid integer NOT NULL,
  city varchar(60) NOT NULL,
  postalcode varchar(5) NOT NULL,
  address varchar(128) NULL,
  reference varchar(128) NULL,
  updatedfinance boolean NULL,
  financeemailsent boolean NULL,
  statusid integer NOT NULL,
  oscstatusid integer NULL,
  dynamicsoscstatusid varchar(128) NULL,
  dynamicsstatusid varchar(128) NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  financeministrynumber varchar(30) NULL,
  osctypeconstitutionid integer NOT NULL,
  PRIMARY KEY (oscprofileid),
  CONSTRAINT fk_oscprofile_userprofile FOREIGN KEY (userprofileid) REFERENCES userprofile(userprofileid),
  CONSTRAINT fk_oscprofile_country FOREIGN KEY (countryid) REFERENCES country(countryid),
  CONSTRAINT fk_oscprofile_state FOREIGN KEY (stateid) REFERENCES state(stateid),
  CONSTRAINT fk_oscprofile_osctype FOREIGN KEY (osctypeid) REFERENCES osctype(osctypeid),
  CONSTRAINT fk_oscprofile_actionline FOREIGN KEY (actionlineid) REFERENCES actionline(actionlineid),
  CONSTRAINT fk_oscprofile_actionlinesecondary FOREIGN KEY (actionlinesecondaryid) REFERENCES actionlinesecondary(actionlinesecondaryid),
  CONSTRAINT fk_oscprofile_osctypeconstitution FOREIGN KEY (osctypeconstitutionid) REFERENCES osctypeconstitution(osctypeconstitutionid),
  CONSTRAINT fk_oscprofile_oscstatus FOREIGN KEY (oscstatusid) REFERENCES oscstatus(oscstatusid)
);

-- Representative seed data (NOT production catalog content).

INSERT INTO oscstatus (oscstatusid, dynamicsoscstatusid, name, description, statusid, dynamicsstatusid, usercreateid, datetimecreate)
VALUES
  (1, '206430000', 'Enviado', 'Enviado', 1, '1', '1', now()),
  (2, '206430001', 'En revisión', 'En revisión', 1, '1', '1', now()),
  (3, '206430002', 'Aprobado', 'Aprobado', 1, '1', '1', now()),
  (4, '206430003', 'No aprobado', 'No aprobado', 1, '1', '1', now()),
  (5, '206430004', 'Expirado', 'Expirado', 1, '1', '1', now())
ON CONFLICT (oscstatusid) DO UPDATE SET
  dynamicsoscstatusid = EXCLUDED.dynamicsoscstatusid,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  statusid = EXCLUDED.statusid,
  dynamicsstatusid = EXCLUDED.dynamicsstatusid,
  usercreateid = EXCLUDED.usercreateid;

INSERT INTO osctype (osctypeid, dynamicsosctypeid, name, description, statusid, dynamicsstatusid, usercreateid, datetimecreate)
VALUES
  (1, '1', 'OSC', 'Organización de la Sociedad Civil', 1, '1', '1', now()),
  (2, '2', 'Fundación', 'Fundación', 1, '1', '1', now()),
  (3, '3', 'Asociación Civil', 'Asociación Civil', 1, '1', '1', now())
ON CONFLICT (osctypeid) DO UPDATE SET
  dynamicsosctypeid = EXCLUDED.dynamicsosctypeid,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  statusid = EXCLUDED.statusid,
  dynamicsstatusid = EXCLUDED.dynamicsstatusid,
  usercreateid = EXCLUDED.usercreateid;

INSERT INTO osctypeconstitution (osctypeconstitutionid, dynamicsosctypeconstitutionid, name, description, statusid, dynamicsstatusid, usercreateid, datetimecreate)
VALUES
  (1, NULL, 'A.C.', 'Asociación Civil', 1, '1', '1', now()),
  (2, NULL, 'I.A.P.', 'Institución de Asistencia Privada', 1, '1', '1', now()),
  (3, NULL, 'A.B.P.', 'Asociación Beneficencia Privada', 1, '1', '1', now()),
  (4, NULL, 'S.C.', 'Sociedad Civil', 1, '1', '1', now())
ON CONFLICT (osctypeconstitutionid) DO UPDATE SET
  dynamicsosctypeconstitutionid = EXCLUDED.dynamicsosctypeconstitutionid,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  statusid = EXCLUDED.statusid,
  dynamicsstatusid = EXCLUDED.dynamicsstatusid,
  usercreateid = EXCLUDED.usercreateid;

INSERT INTO actionline (actionlineid, dynamicsactionlineid, name, description, statusid, dynamicsstatusid, usercreateid, datetimecreate)
VALUES
  (1, NULL, 'Educación', 'Educación', 1, '1', '1', now()),
  (2, NULL, 'Salud', 'Salud', 1, '1', '1', now()),
  (3, NULL, 'Protección infantil', 'Protección infantil', 1, '1', '1', now())
ON CONFLICT (actionlineid) DO UPDATE SET
  dynamicsactionlineid = EXCLUDED.dynamicsactionlineid,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  statusid = EXCLUDED.statusid,
  dynamicsstatusid = EXCLUDED.dynamicsstatusid,
  usercreateid = EXCLUDED.usercreateid;

INSERT INTO actionlinesecondary (actionlinesecondaryid, dynamicsactionlinesecondaryid, name, description, statusid, dynamicsstatusid, usercreateid, datetimecreate)
VALUES
  (1, NULL, 'Arte y cultura', 'Arte y cultura', 1, '1', '1', now()),
  (2, NULL, 'Deporte', 'Deporte', 1, '1', '1', now()),
  (3, NULL, 'Medio ambiente', 'Medio ambiente', 1, '1', '1', now())
ON CONFLICT (actionlinesecondaryid) DO UPDATE SET
  dynamicsactionlinesecondaryid = EXCLUDED.dynamicsactionlinesecondaryid,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  statusid = EXCLUDED.statusid,
  dynamicsstatusid = EXCLUDED.dynamicsstatusid,
  usercreateid = EXCLUDED.usercreateid;

INSERT INTO state (stateid, dynamicsstateid, dynamicscountryid, name, description, statusid, dynamicsstatusid, countryid, usercreateid, datetimecreate)
VALUES
  (1, NULL, NULL, 'Ciudad de México', 'Ciudad de México', 1, '1', 4, '1', now()),
  (2, NULL, NULL, 'Jalisco', 'Jalisco', 1, '1', 4, '1', now()),
  (3, NULL, NULL, 'Nuevo León', 'Nuevo León', 1, '1', 4, '1', now()),
  (4, NULL, NULL, 'Puebla', 'Puebla', 1, '1', 4, '1', now())
ON CONFLICT (stateid) DO UPDATE SET
  dynamicsstateid = EXCLUDED.dynamicsstateid,
  dynamicscountryid = EXCLUDED.dynamicscountryid,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  statusid = EXCLUDED.statusid,
  dynamicsstatusid = EXCLUDED.dynamicsstatusid,
  countryid = EXCLUDED.countryid,
  usercreateid = EXCLUDED.usercreateid;
