-- OSC Legal Base schema: one row per OSC, country-conditional required field.
-- Applied on API startup by the schema initializer.
-- NOTE: this file is DDL-only. Fixture data lives in db/seeds/003_osc_legalbase_fixture.sql.

CREATE TABLE IF NOT EXISTS legalbase (
  legalbaseid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  userprofileid integer NOT NULL,
  oscprofileid integer NULL,
  organizationconstitutiondate timestamp(3) NOT NULL,
  lastprotocolizationdate timestamp(3) NULL,
  isauthorized boolean NOT NULL,
  goubernamentalauthorizationdate timestamp(3) NOT NULL,
  socialobjetive varchar(1024) NOT NULL,
  statusid integer NOT NULL,
  usercreated varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdatedid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (legalbaseid),
  CONSTRAINT fk_legalbase_userprofile FOREIGN KEY (userprofileid) REFERENCES userprofile(userprofileid),
  CONSTRAINT fk_legalbase_oscprofile FOREIGN KEY (oscprofileid) REFERENCES oscprofile(oscprofileid)
);
