-- OSC Legal Base schema: one row per OSC, country-conditional required field.
-- Applied on API startup by the schema initializer.

CREATE TABLE IF NOT EXISTS legalbase (
  legalbaseid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  userprofileid integer NOT NULL,
  oscprofileid integer NULL,
  organizationconstitutiondate timestamp(3) NOT NULL,
  lastprotocolizationdate timestamp(3) NULL,
  isauthorized boolean NOT NULL,
  goubernamentalauthorizationdate timestamp(3) NOT NULL,
  socialobjetive varchar(1024) NOT NULL,
  statusid integer NOT NULL,
  usercreated varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdatedid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (legalbaseid),
  CONSTRAINT fk_legalbase_userprofile FOREIGN KEY (userprofileid) REFERENCES userprofile(userprofileid),
  CONSTRAINT fk_legalbase_oscprofile FOREIGN KEY (oscprofileid) REFERENCES oscprofile(oscprofileid)
);

-- Representative fixture row for the PR #8 auth fixture user (qa.auth@dibujando.test,
-- userprofileid 1 after fresh seed) so the Legal Base section has real data to exercise.
INSERT INTO legalbase (
  legalbaseid,
  userprofileid,
  oscprofileid,
  organizationconstitutiondate,
  lastprotocolizationdate,
  isauthorized,
  goubernamentalauthorizationdate,
  socialobjetive,
  statusid,
  usercreated,
  datetimecreate
)
VALUES (
  1,
  1,
  NULL,
  '2020-01-15',
  '2022-06-30',
  true,
  '2023-01-01',
  'Promover el desarrollo integral de niñas, niños, adolescentes y jóvenes a través de programas educativos, culturales y de salud.',
  1,
  '1',
  now()
)
ON CONFLICT (legalbaseid) DO UPDATE SET
  userprofileid = EXCLUDED.userprofileid,
  oscprofileid = EXCLUDED.oscprofileid,
  organizationconstitutiondate = EXCLUDED.organizationconstitutiondate,
  lastprotocolizationdate = EXCLUDED.lastprotocolizationdate,
  isauthorized = EXCLUDED.isauthorized,
  goubernamentalauthorizationdate = EXCLUDED.goubernamentalauthorizationdate,
  socialobjetive = EXCLUDED.socialobjetive,
  statusid = EXCLUDED.statusid,
  usercreated = EXCLUDED.usercreated;

-- Keep the identity sequence ahead of the seeded fixture so API inserts do not collide.
SELECT setval('legalbase_legalbaseid_seq', (SELECT MAX(legalbaseid) FROM legalbase));
