-- Finance and Institutional Base catalog tables.
-- These are consumed by upcoming Finance / InstitutionalBase feature work;
-- this script only creates the DDL so the real production catalog seed
-- (db/seeds/000_catalogs.sql) can populate them.
-- Applied on API startup by the schema initializer.
-- NOTE: this file is DDL-only. Catalog data lives in db/seeds/000_catalogs.sql.

CREATE TABLE IF NOT EXISTS agegroup (
  agegroupid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  agegroupname varchar(128) NOT NULL,
  "order" integer NOT NULL,
  foraplication boolean DEFAULT false NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (agegroupid)
);

CREATE TABLE IF NOT EXISTS personalsituation (
  personalsituationid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  personalsituationname varchar(128) NOT NULL,
  "order" integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (personalsituationid)
);

CREATE TABLE IF NOT EXISTS financingtype (
  financingtypeid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  dynamicsfinancingtypeid varchar(128) NOT NULL,
  name varchar(128) NOT NULL,
  description varchar(128) NOT NULL,
  statusid integer NOT NULL,
  dynamicsstatusid varchar(128) NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (financingtypeid)
);

CREATE TABLE IF NOT EXISTS donortype (
  donortypeid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  name varchar(128) NOT NULL,
  "order" integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (donortypeid)
);

CREATE TABLE IF NOT EXISTS donationtype (
  donationtypeid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  name varchar(128) NOT NULL,
  "order" integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (donationtypeid)
);

CREATE TABLE IF NOT EXISTS incomeexpenseconcept (
  incomeexpenseconceptid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  concepttypeid integer NOT NULL,
  name varchar(128) NOT NULL,
  "order" integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (incomeexpenseconceptid)
);

CREATE TABLE IF NOT EXISTS financedate (
  financedateid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  activity varchar(128) NOT NULL,
  description varchar(512) NOT NULL,
  startday integer NOT NULL,
  startmonth integer NOT NULL,
  endday integer NULL,
  endmonth integer NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (financedateid)
);
