-- OSC Institutional Base schema: main profile row plus four child collections.
-- Applied on API startup by the schema initializer.
-- NOTE: this file is DDL-only. Fixture data lives in db/seeds/004_osc_institutionalbase_fixture.sql.

CREATE TABLE IF NOT EXISTS institutionalbase (
  institutionalbaseid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  userprofileid integer NOT NULL,
  oscprofileid integer NULL,
  organizationhistory varchar(2500) NOT NULL,
  organizationmission varchar(450) NOT NULL,
  organizationvision varchar(450) NOT NULL,
  organizationvalues varchar(300) NOT NULL,
  describeproblematic varchar(2500) NOT NULL,
  describemodel varchar(3200) NOT NULL,
  totalpopulationserved integer NOT NULL,
  atentionminage integer NOT NULL,
  atentionmaxage integer NOT NULL,
  poblationprofile varchar(90) NOT NULL,
  poblationpercentage double precision NOT NULL,
  hasvolunterprogram boolean NOT NULL,
  wantvolunterprogram boolean NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  hasstrengtheningprogram boolean NULL,
  strengtheningtype varchar(1024) NULL,
  strengtheningorganizationname varchar(200) NULL,
  strengtheningcourseyear varchar(200) NULL,
  hassocialinvestmentadvisor boolean NULL,
  hashumanrightsapproach boolean NULL,
  PRIMARY KEY (institutionalbaseid),
  CONSTRAINT fk_institutionalbase_userprofile FOREIGN KEY (userprofileid) REFERENCES userprofile(userprofileid),
  CONSTRAINT fk_institutionalbase_oscprofile FOREIGN KEY (oscprofileid) REFERENCES oscprofile(oscprofileid)
);

CREATE TABLE IF NOT EXISTS interventionmodelprograms (
  interventionmodelprogramsid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  institutionalbaseid integer NOT NULL,
  programname varchar(128) NOT NULL,
  description varchar(256) NOT NULL,
  mainactivity varchar(256) NOT NULL,
  verificationmeans varchar(256) NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (interventionmodelprogramsid),
  CONSTRAINT fk_interventionmodelprograms_institutionalbase FOREIGN KEY (institutionalbaseid) REFERENCES institutionalbase(institutionalbaseid)
);

CREATE TABLE IF NOT EXISTS populationserved (
  populationservedid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  institutionalbaseid integer NOT NULL,
  agegroupid integer NOT NULL,
  femenine integer NULL,
  male integer NULL,
  notbinary integer NULL,
  total integer NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (populationservedid),
  CONSTRAINT fk_populationserved_institutionalbase FOREIGN KEY (institutionalbaseid) REFERENCES institutionalbase(institutionalbaseid),
  CONSTRAINT fk_populationserved_agegroup FOREIGN KEY (agegroupid) REFERENCES agegroup(agegroupid)
);

CREATE TABLE IF NOT EXISTS operativeteam (
  operativeteamid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  institutionalbaseid integer NOT NULL,
  personalsituationid integer NOT NULL,
  innomina integer NOT NULL,
  forfees integer NOT NULL,
  feesforassimilable integer NOT NULL,
  volunteers integer NOT NULL,
  practitionersorsocialservice integer NOT NULL,
  total integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (operativeteamid),
  CONSTRAINT fk_operativeteam_institutionalbase FOREIGN KEY (institutionalbaseid) REFERENCES institutionalbase(institutionalbaseid),
  CONSTRAINT fk_operativeteam_personalsituation FOREIGN KEY (personalsituationid) REFERENCES personalsituation(personalsituationid)
);

CREATE TABLE IF NOT EXISTS volunteeractivities (
  volunteeractivitiesid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  institutionalbaseid integer NOT NULL,
  activitytype varchar(128) NOT NULL,
  numberofvolunteer integer NULL,
  servicehoursrequired integer NULL,
  investmentrequired double precision NULL,
  idealvolunteerprofile varchar(128) NOT NULL,
  specialprovitions varchar(256) NOT NULL,
  statusid integer NOT NULL,
  usercreatedid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (volunteeractivitiesid),
  CONSTRAINT fk_volunteeractivities_institutionalbase FOREIGN KEY (institutionalbaseid) REFERENCES institutionalbase(institutionalbaseid)
);
