-- OSC Government schema: main governance contacts row plus repeatable governing-body members.
-- Applied on API startup by the schema initializer.
-- NOTE: this file is DDL-only. Fixture data lives in db/seeds/005_osc_government_fixture.sql.

CREATE TABLE IF NOT EXISTS government (
  governmentid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  userprofileid integer NOT NULL,
  oscprofileid integer NULL,
  presidencyname varchar(128) NOT NULL,
  presidencyemail varchar(128) NOT NULL,
  legalrepresentativename varchar(128) NOT NULL,
  legalrepresentativeemail varchar(128) NOT NULL,
  executivegeneralmanagementname varchar(128) NOT NULL,
  executivegeneralmanagementemail varchar(128) NOT NULL,
  programandprojectoperationname varchar(128) NOT NULL,
  programandprojectoperationemail varchar(128) NOT NULL,
  institutionaldevelopmentname varchar(128) NULL,
  institutionaldevelopmentemail varchar(128) NULL,
  numberofmembers integer NOT NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (governmentid),
  CONSTRAINT fk_government_userprofile FOREIGN KEY (userprofileid) REFERENCES userprofile(userprofileid),
  CONSTRAINT fk_government_oscprofile FOREIGN KEY (oscprofileid) REFERENCES oscprofile(oscprofileid)
);

CREATE TABLE IF NOT EXISTS governingbody (
  governingbodyid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  governmentid integer NOT NULL,
  name varchar(120) NOT NULL,
  position varchar(128) NOT NULL,
  membersince integer NOT NULL,
  ismemberofotherbody boolean NOT NULL,
  memberofotherbody varchar(128) NULL,
  rfc varchar(25) NULL,
  statusid integer NOT NULL,
  usercreateid varchar(128) NOT NULL,
  datetimecreate timestamp(3) NOT NULL,
  userupdateid varchar(128) NULL,
  datetimelastupdate timestamp(3) NULL,
  PRIMARY KEY (governingbodyid),
  CONSTRAINT fk_governingbody_government FOREIGN KEY (governmentid) REFERENCES government(governmentid)
);
