// @budget-exception(250): generated Kysely DB types; splitting fragments the schema cluster.
// approved-by: executor · 2026-07-11 · pending PR
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from 'kysely';
export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;
export interface Actionline {
  actionlineid: Generated<number>;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicsactionlineid: string | null;
  dynamicsstatusid: string;
  name: string;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Actionlinesecondary {
  actionlinesecondaryid: Generated<number>;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicsactionlinesecondaryid: string | null;
  dynamicsstatusid: string;
  name: string;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Answer {
  answerid: Generated<number>;
  answerstring: string;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  iscorrect: boolean;
  order: number;
  questionid: number;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Aspnetroles {
  id: string;
  name: string;
}
export interface Aspnetuserroles {
  roleid: string;
  userid: string;
}
export interface Aspnetusers {
  accessfailedcount: number;
  email: string | null;
  emailconfirmed: boolean;
  id: string;
  lockoutenabled: boolean;
  lockoutenddateutc: Timestamp | null;
  passwordhash: string | null;
  phonenumber: string | null;
  phonenumberconfirmed: boolean;
  securitystamp: string | null;
  twofactorenabled: boolean;
  username: string;
}
export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  security_stamp_at_issue: string;
  user_id: string;
}
export interface Country {
  countryid: Generated<number>;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicscountryid: string | null;
  dynamicsstatusid: string;
  name: string;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Legalbase {
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  goubernamentalauthorizationdate: Timestamp;
  isauthorized: boolean;
  lastprotocolizationdate: Timestamp | null;
  legalbaseid: Generated<number>;
  organizationconstitutiondate: Timestamp;
  oscprofileid: number | null;
  socialobjetive: string;
  statusid: number;
  usercreated: string;
  userprofileid: number;
  userupdatedid: string | null;
}
export interface Logtriedquestions {
  datetimecreate: Timestamp;
  datetimeedit: Timestamp | null;
  datetimetried: Timestamp;
  iptried: string;
  iscorrect: boolean;
  logtriedquestionsid: Generated<number>;
}
export interface Oscprofile {
  actionlineid: number | null;
  actionlinesecondaryid: number | null;
  address: string | null;
  city: string;
  contactemail: string;
  contactmobilephone: string | null;
  contactname: string;
  contactposition: string;
  contacttelephone: string | null;
  contacttelephoneext: string | null;
  countryid: number;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  dynamicsoscprofileid: string | null;
  dynamicsoscstatusid: string | null;
  dynamicsstatusid: string | null;
  email: string;
  financeemailsent: boolean | null;
  financeministrynumber: string | null;
  name: string;
  nationalregistrynumber: string;
  oscprofileid: Generated<number>;
  oscstatusid: number | null;
  osctypeconstitutionid: number;
  osctypeid: number;
  postalcode: string;
  reference: string | null;
  socialreason: string;
  stateid: number;
  statusid: number;
  updatedfinance: boolean | null;
  usercreateid: string;
  userprofileid: number;
  userupdateid: string | null;
}
export interface Oscstatus {
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicsoscstatusid: string;
  dynamicsstatusid: string;
  name: string;
  oscstatusid: Generated<number>;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Osctype {
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicsosctypeid: string;
  dynamicsstatusid: string;
  name: string;
  osctypeid: Generated<number>;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Osctypeconstitution {
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicsosctypeconstitutionid: string | null;
  dynamicsstatusid: string;
  name: string;
  osctypeconstitutionid: Generated<number>;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Question {
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  order: number;
  questionid: Generated<number>;
  questionstring: string;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface State {
  countryid: number;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  description: string;
  dynamicscountryid: string | null;
  dynamicsstateid: string | null;
  dynamicsstatusid: string;
  name: string;
  stateid: Generated<number>;
  statusid: number;
  usercreateid: string;
  userupdateid: string | null;
}
export interface Userprofile {
  countryid: number | null;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  email: string;
  externalid: string | null;
  fileid: number | null;
  fullinstitutionname: string;
  institutionname: string;
  internalid: string;
  nationalregistrynumber: string | null;
  statusid: number;
  usercreateid: string;
  userprofileid: Generated<number>;
  userupdateid: string | null;
}
export interface DB {
  actionline: Actionline;
  actionlinesecondary: Actionlinesecondary;
  answer: Answer;
  aspnetroles: Aspnetroles;
  aspnetuserroles: Aspnetuserroles;
  aspnetusers: Aspnetusers;
  auth_sessions: AuthSessions;
  country: Country;
  legalbase: Legalbase;
  logtriedquestions: Logtriedquestions;
  oscprofile: Oscprofile;
  oscstatus: Oscstatus;
  osctype: Osctype;
  osctypeconstitution: Osctypeconstitution;
  question: Question;
  state: State;
  userprofile: Userprofile;
}
