/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Aspnetroles {
  id: string;
  name: string;
}

export interface Aspnetuserroles {
  roleid: string;
  userid: string;
}

export interface Aspnetusers {
  accessfailedcount: number;
  email: string | null;
  emailconfirmed: boolean;
  id: string;
  lockoutenabled: boolean;
  lockoutenddateutc: Timestamp | null;
  passwordhash: string | null;
  phonenumber: string | null;
  phonenumberconfirmed: boolean;
  securitystamp: string | null;
  twofactorenabled: boolean;
  username: string;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  security_stamp_at_issue: string;
  user_id: string;
}

export interface Userprofile {
  countryid: number | null;
  datetimecreate: Timestamp;
  datetimelastupdate: Timestamp | null;
  email: string;
  externalid: string | null;
  fileid: number | null;
  fullinstitutionname: string;
  institutionname: string;
  internalid: string;
  nationalregistrynumber: string | null;
  statusid: number;
  usercreateid: string;
  userprofileid: Generated<number>;
  userupdateid: string | null;
}

export interface DB {
  aspnetroles: Aspnetroles;
  aspnetuserroles: Aspnetuserroles;
  aspnetusers: Aspnetusers;
  auth_sessions: AuthSessions;
  userprofile: Userprofile;
}
